version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budgie_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  test:
    build: .
    command: mix test
    environment:
      MIX_ENV: test
      DATABASE_HOST: "db"    # Overrides the default "localhost" for testing in Docker
      # MIX_TEST_PARTITION can be set externally if you're running tests in parallel
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_test_data:

